<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE manifest [
    <!ELEMENT manifest (module, version, license, description, author+, dependencies?, contents)>
    <!ATTLIST manifest
        version CDATA   #REQUIRED
    >

    <!ELEMENT module (#PCDATA)>

    <!ELEMENT version (release, api, stability)>

    <!ELEMENT stability (release, api)>

    <!ELEMENT release (#PCDATA)>

    <!ELEMENT api (#PCDATA)>

    <!ELEMENT description (#PCDATA)>

    <!ELEMENT author (name, email?, homepage?)>

    <!ELEMENT name (#PCDATA)>
    
    <!ELEMENT email (#PCDATA)>
    
    <!ELEMENT hompeage (#PCDATA)>

    <!ELEMENT dependencies (dependency*)>

    <!ELEMENT dependency EMPTY>
    <!ATTLIST dependency
        module  CDATA   #REQUIRED
        version CDATA   #REQUIRED
    >

    <!ELEMENT contents (directory*, file*)>
    
    <!ELEMENT directory (directory*, file*)>
    <!ATTLIST directory
        name    CDATA   #REQUIRED
    >

    <!ELEMENT file EMPTY>
    <!ATTLIST file
        name    CDATA   #REQUIRED
        md5sum  CDATA   #REQUIRED
    >
]>

<manifest version="1.0">
    <module>Security</module>

    <version>
        <release>0.2.4</release>
        <api>0.2</api>

        <stability>
            <release>stable</release>
            <api>stable</api>
        </stability>
    </version>

    <license uri="http://www.fsf.org/licensing/licenses/agpl-3.0.html">Affero GNU General Public License</license>

    <description>Server side modules infrastructure.</description>

    <author>
        <name>meh.</name>
        <email>meh.ffff@gmail.com</email>
        <homepage>http://meh.doesntexist.org</homepage>
    </author>

    <contents>
        <file name="main.js" md5sum="322f2153e0a73559f7cfbb33cb2a7340"/>
        <file name="main.php" md5sum="bd8bcce470c0064429af0282ba361be9"/>
        <file name="utils.php" md5sum="275879edc8283234da5b1fb48ab918bd"/>

        <directory name="resources">
            <file name="config.php" md5sum="5b0efec8ae6b0d9c320d4b3b6f675f94"/>
            <file name="style.css" md5sum="d41d8cd98f00b204e9800998ecf8427e"/>
            <file name="template.php" md5sum="8440f67c8837983d5488e96f10417409"/>
        </directory>
    </contents>
</module>
